language: generic 
sudo: required
services: 
  - docker
before_install:
  - docker build -t louiszhang97/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true louiszhang97/docker-react npm run test